env: local
server:
  #  host: 0.0.0.0
  host: 127.0.0.1
  port: 1534
  prefix: /api
security:
  api_sign:
    app_key: 123456
    app_security: 123456
jwt:
  key: QQYnRFerJTSEcrfB89fw8prOaObmrch8

mysql:
#  dsn: 用户名:密码@tcp(127.0.0.1:3306)/数据库名?charset=utf8mb4&parseTime=True&loc=Local
  dsn: test:test@tcp(127.0.0.1:3306)/test?charset=utf8mb4&parseTime=True&loc=Local
  debug: True
redis:
  addr: 127.0.0.1:6379
  password: ""
  db: 0
  read_timeout: 0.2s
  write_timeout: 0.2s

log:
  log_level: debug
  log_file_name: "./logs/server.log"
  max_backups: 30
  max_age: 7
  max_size: 1024
  compress: true

minio:
  endpoint: xx.xx.xx.xx:9000
  access_key_id: xxxxxxxxxxxxxxxxxxxxxxx
  secret_access_key: xxxxxxxxxxxxxxxxxxxx
  bucket_name: xx
  use_ssl: false